<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<<<<<<< HEAD
<testsuite hostname="laptop-ribas" name="Default test" tests="3" failures="1" timestamp="3 Jul 2015 01:34:55 GMT" time="33.644" errors="0">
  <testcase name="criarSkuPart1" time="0.032" classname="br.com.brm.scp.api.service.test.SkuServiceMockTest"/>
  <testcase name="criarSkuPart2" time="0.033" classname="br.com.brm.scp.api.service.test.SkuServiceMockTest"/>
  <testcase name="skuExistenteException" time="32.354" classname="br.com.brm.scp.api.service.test.SkuServiceMockTest">
    <failure type="org.testng.TestException" message="
Expected exception br.com.brm.scp.api.exceptions.SkuExistenteException but got org.testng.TestException: 
Method SkuServiceMockTest.skuExistenteException()[pri:0, instance:br.com.brm.scp.api.service.test.SkuServiceMockTest@618b19ad] should have thrown an exception of class br.com.brm.scp.api.exceptions.SkuExistenteException">
      <![CDATA[org.testng.TestException: 
Expected exception br.com.brm.scp.api.exceptions.SkuExistenteException but got org.testng.TestException: 
Method SkuServiceMockTest.skuExistenteException()[pri:0, instance:br.com.brm.scp.api.service.test.SkuServiceMockTest@618b19ad] should have thrown an exception of class br.com.brm.scp.api.exceptions.SkuExistenteException
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1497)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1245)
=======
<testsuite hostname="Leon" name="Default test" tests="1" failures="1" timestamp="7 Jul 2015 17:12:21 GMT" time="0.845" errors="0">
  <testcase name="testCreate" time="0.015" classname="br.com.brm.scp.api.service.test.ItemSeviceMockTest">
    <failure type="java.lang.IllegalArgumentException" message="item.nome">
      <![CDATA[java.lang.IllegalArgumentException: item.nome
	at org.springframework.util.Assert.notNull(Assert.java:112)
	at br.com.brm.scp.mock.api.service.impl.ItemServiceMockImpl.create(ItemServiceMockImpl.java:34)
	at br.com.brm.scp.api.service.test.ItemSeviceMockTest.testCreate(ItemSeviceMockTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:200)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:212)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
>>>>>>> 148b49415e6554a58d341b0472f668de1c45efa2
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
<<<<<<< HEAD
Caused by: org.testng.TestException: 
Method SkuServiceMockTest.skuExistenteException()[pri:0, instance:br.com.brm.scp.api.service.test.SkuServiceMockTest@618b19ad] should have thrown an exception of class br.com.brm.scp.api.exceptions.SkuExistenteException
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1512)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:754)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	... 16 more
=======
>>>>>>> 148b49415e6554a58d341b0472f668de1c45efa2
]]>
    </failure>
  </testcase> <!-- testCreate -->
</testsuite> <!-- Default test -->
