<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<<<<<<< HEAD
<testsuite hostname="Leon" name="br.com.brm.scp.api.service.test.UsuarioSeviceMockTest" tests="4" failures="0" timestamp="26 Apr 2015 20:58:40 GMT" time="0.028" errors="1">
  <testcase name="update" time="0.004" classname="br.com.brm.scp.api.service.test.UsuarioSeviceMockTest"/>
  <testcase name="delete" time="0.001" classname="br.com.brm.scp.api.service.test.UsuarioSeviceMockTest"/>
  <testcase name="find" time="0.012" classname="br.com.brm.scp.api.service.test.UsuarioSeviceMockTest"/>
  <testcase name="create" time="0.011" classname="br.com.brm.scp.api.service.test.UsuarioSeviceMockTest">
    <error type="java.lang.AssertionError" message="expected:&lt;a&gt; but was:&lt;v&gt;">
      <![CDATA[java.lang.AssertionError: expected:<a> but was:<v>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at br.com.brm.scp.api.service.test.UsuarioSeviceMockTest.create(UsuarioSeviceMockTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:200)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:212)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- create -->
=======
<testsuite hostname="laptop-ribas" name="br.com.brm.scp.api.service.test.UsuarioSeviceMockTest" tests="4" failures="0" timestamp="26 Apr 2015 20:19:08 GMT" time="0.016" errors="0">
  <testcase name="find" time="0.003" classname="br.com.brm.scp.api.service.test.UsuarioSeviceMockTest"/>
  <testcase name="delete" time="0.003" classname="br.com.brm.scp.api.service.test.UsuarioSeviceMockTest"/>
  <testcase name="update" time="0.003" classname="br.com.brm.scp.api.service.test.UsuarioSeviceMockTest"/>
  <testcase name="create" time="0.007" classname="br.com.brm.scp.api.service.test.UsuarioSeviceMockTest"/>
>>>>>>> 239b4f3807ec9728dc4e60d3860c9f25f5f94ab0
</testsuite> <!-- br.com.brm.scp.api.service.test.UsuarioSeviceMockTest -->
